version: "3"

services:

  ruby:
    #image: ruby:3.2.1
    build:
      context: ${PWD}/_d/ruby
    networks: [rails1-network]
    ports: ["9300:3000"]
    volumes:
      - ${PWD}/app:/usr/src/app

  nginx:
    #image: nginx:1.22.1
    build: ${PWD}/_d/nginx
    ports: ["${NGINX_FWD_S_PORT}:443"]
    restart: always
    depends_on: [ruby]
    networks: [rails1-network]
    volumes:
      - ${PWD}/_ssl:/etc/nginx/ssl
      - ${PWD}/app/blog2/public:/var/www/app
      - ${PWD}/_d/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/_d/nginx/conf.d_default.conf:/etc/nginx/conf.d/default.conf

networks:
  rails1-network:
    driver: bridge
